const products = [
  "The Legend of Zelda: Breath of the Wild",
  "Super Mario Odyssey",
  "Animal Crossing: New Horizons",
  "Mario Kart 8 Deluxe",
  "Splatoon 2",
  "Super Smash Bros. Ultimate",
  "Pokémon Sword",
  "Pokémon Shield",
  "Luigi's Mansion 3",
  "Super Mario Maker 2",
  "Fire Emblem: Three Houses",
  "Xenoblade Chronicles 2",
  "Astral Chain",
  "Octopath Traveler",
  "Hyrule Warriors: Age of Calamity",
  "Ring Fit Adventure",
  "Paper Mario: The Origami King",
  "Mario Tennis Aces",
  "Mario Party Superstars",
  "Super Mario 3D World + Bowser's Fury",
  "New Pokémon Snap",
  "Monster Hunter Rise",
  "Legend of Zelda: Skyward Sword HD",
  "Bravely Default II",
  "Metroid Dread",
  "Bayonetta 3",
  "No More Heroes III",
  "Pikmin 3 Deluxe",
  "Daemon X Machina",
  "Monster Hunter Stories 2: Wings of Ruin",
  "Shin Megami Tensei V",
  "Splatoon 3",
  "Advance Wars 1+2: Re-Boot Camp",
  "The Elder Scrolls V: Skyrim",
  "Doom Eternal",
  "Overwatch",
  "Fortnite",
  "Minecraft",
  "Rocket League",
  "Apex Legends",
  "FIFA 22",
  "NBA 2K22",
  "Madden NFL 22",
  "Crash Bandicoot 4: It's About Time",
  "Spyro Reignited Trilogy",
  "Tony Hawk's Pro Skater 1 + 2",
  "Mortal Kombat 11",
  "Street Fighter V: Champion Edition",
  "Guilty Gear -Strive-",
  "Tekken 7",
  "Devil May Cry 5 Special Edition",
  "Resident Evil Village",
  "Final Fantasy VII Remake Intergrade",
  "Ratchet & Clank: Rift Apart",
  "Demon's Souls",
  "Returnal",
  "Gran Turismo 7",
  "Horizon Forbidden West",
  "God of War Ragnarok",
  "Spider-Man: Miles Morales",
  "Sackboy: A Big Adventure",
  "LittleBigPlanet 3",
  "Ghost of Tsushima",
  "Death Stranding Director's Cut",
  "The Last of Us Part II",
  "Ghostwire: Tokyo",
  "Kena: Bridge of Spirits",
  "Hogwarts Legacy",
  "Far Cry 6",
  "Assassin's Creed Valhalla",
  "Cyberpunk 2077",
  "Watch Dogs: Legion",
  "Hitman 3",
  "Resident Evil 7: Biohazard",
  "Yakuza: Like a Dragon",
  "Scarlet Nexus",
  "Tales of Arise",
  "Nier Replicant ver.1.22474487139...",
  "Persona 5 Strikers",
  "Lost Judgment",
  "Bravely Default II",
  "Monster Hunter Rise",
  "Shin Megami Tensei III: Nocturne HD Remaster",
  "NEO: The World Ends with You",
  "Legend of Mana Remastered",
  "Final Fantasy XIV Online: Endwalker",
  "Scarlet Nexus",
  "Tales of Arise",
  "Nier Replicant ver.1.22474487139...",
  "Persona 5 Strikers",
  "Lost Judgment",
  "Hades",
  "Celeste",
  "Hollow Knight",
  "Dead Cells",
  "Ori and the Will of the Wisps",
  "Shovel Knight",
  "Stardew Valley",
  "Cuphead",
  "Undertale",
];

const descriptions = [
  "Un épico juego de aventuras en un vasto mundo abierto donde los jugadores exploran Hyrule, resuelven acertijos y combaten contra enemigos mientras buscan salvar el reino de la calamidad.",
  "Únete a Mario en una aventura a través de varios reinos en su búsqueda para rescatar a la Princesa Peach de Bowser.",
  "Crea tu propio paraíso en una isla desierta donde puedes pescar, atrapar insectos, decorar tu hogar y más.",
  "Compite en emocionantes carreras con tus personajes favoritos de Nintendo y usa objetos para ganar ventaja sobre tus oponentes.",
  "Forma equipo con amigos para participar en batallas de tinta multijugador en este juego de disparos colorido y frenético.",
  "Reúne a tus personajes favoritos de Nintendo en un juego de lucha lleno de acción con una amplia variedad de escenarios y modos de juego.",
  "Embárcate en una aventura para convertirte en el Campeón de Galar y derrotar al Campeón de la Liga Pokémon.",
  "Elige tu inicial y explora el vasto mundo de Galar en busca de nuevos Pokémon y desafíos.",
  "Ayuda a Luigi a rescatar a sus amigos de los fantasmas en esta encantadora y espeluznante aventura.",
  "Crea y comparte tus propios niveles de Mario en esta entrega de la serie Super Mario Maker.",
  "Únete a una de las tres casas en la Academia de Oficiales y participa en batallas estratégicas para determinar el futuro de Fódlan.",
  "Embárcate en una épica búsqueda para encontrar la Elysium en un mundo lleno de criaturas titánicas y misterios antiguos.",
  "Combate contra invasores interdimensionales como un miembro de la fuerza policial especial conocida como Neuron.",
  "Explora el vasto mundo de Osterra y descubre la historia única de cada uno de los ocho protagonistas.",
  "Únete a Link y Zelda en la batalla contra la calamidad que asola Hyrule en este juego de acción y estrategia.",
  "Ponte en forma mientras te diviertes con una variedad de actividades físicas y minijuegos.",
  "Únete a Mario en una nueva aventura para salvar a la Princesa Peach y derrotar al Rey Olly y su ejército de origami.",
  "Participa en emocionantes partidos de tenis con personajes de la serie Mario.",
  "Reúne a tus amigos y compite en una variedad de minijuegos en línea y fuera de línea.",
  "Únete a Mario y sus amigos en una emocionante aventura en 3D para derrotar a Bowser y salvar a los Espirales.",
  "Explora las islas de la región de Lentil mientras fotografías Pokémon en su entorno natural.",
  "Caza monstruos en vastas tierras salvajes y únete a otros jugadores en línea para enfrentarte a criaturas poderosas.",
  "Únete a Link en su aventura por los cielos en esta remasterización del clásico de Wii.",
  "Únete a un grupo de héroes en un viaje para restablecer los cristales elementales y salvar el mundo de Excillant.",
  "Lucha contra los temibles Metroids y descubre los secretos ocultos en este remake del clásico juego de GameCube.",
  "Disfruta de una nueva entrega de la serie con un nuevo elenco de personajes y un mundo misterioso por explorar.",
  "Embárcate en una nueva aventura en el mundo de Bayonetta y lucha contra criaturas demoníacas con estilo.",
  "Retoma el manto del asesino Travis Touchdown en su lucha contra una serie de peligrosos asesinos.",
  "Ayuda a los Pikmin a reconstruir su hogar y a encontrar nuevas especies en esta versión mejorada del clásico de GameCube.",
  "Pilota tu Arsenal y lucha contra invasores mecánicos en un mundo futurista lleno de acción.",
  "Explora un mundo de fantasía poblado por monstruos y hazte amigo de ellos en esta emocionante aventura RPG.",
  "Descubre un mundo postapocalíptico donde los demonios han invadido la Tierra y lucha por sobrevivir.",
  "Participa en emocionantes batallas de tinta en línea con nuevos modos de juego y escenarios.",
  "Revive los clásicos de la estrategia en tiempo real con gráficos remasterizados y nuevas características.",
  "Explora las vastas tierras de Skyrim y vive aventuras épicas en este juego de rol de mundo abierto.",
  "Lucha contra hordas de demonios en este juego de acción trepidante y lleno de adrenalina.",
  "Únete a un equipo y compite en partidas en línea para alcanzar la victoria en este popular juego de disparos.",
  "Construye y explora tu propio mundo en este juego de construcción y aventuras.",
  "Conduce coches futuristas y compite en partidos de fútbol en esta mezcla única de deportes y carreras.",
  "Únete a un escuadrón y lucha por convertirte en el último equipo en pie en este popular juego de Battle Royale.",
  "Conviértete en una leyenda del fútbol en este simulador realista de la FIFA.",
  "Disfruta del baloncesto profesional con gráficos realistas y una jugabilidad emocionante.",
  "Vive la emoción del fútbol americano con equipos reales y una jugabilidad auténtica.",
  "Ayuda a Crash Bandicoot a detener los malvados planes de Neo Cortex en esta aventura épica.",
  "Revive las aventuras de Spyro en esta colección remasterizada de sus tres primeras aventuras.",
  "Patina como un profesional en esta remasterización de los dos primeros juegos de Tony Hawk's Pro Skater.",
  "Lucha contra tus oponentes en combates uno a uno o en torneos emocionantes.",
  "Elige entre una amplia variedad de personajes y lucha contra tus amigos en este juego de lucha icónico.",
  "Disfruta de intensas batallas en este juego de lucha de alta velocidad.",
  "Demuestra tus habilidades en el combate mano a mano en uno de los juegos de lucha más aclamados.",
  "Lucha contra hordas de demonios en este juego de acción y aventuras lleno de acción.",
  "Explora un misterioso pueblo rural y descubre sus oscuros secretos en esta entrega de la serie Resident Evil.",
  "Disfruta de la edición mejorada de este juego de rol de acción épico con nuevos contenidos.",
  "Embárcate en una nueva aventura interdimensional con Ratchet y Clank en este juego de plataformas y acción.",
  "Explora el oscuro y peligroso mundo de Boletaria en esta remake del clásico juego de PlayStation 3.",
  "Sobrevive en un planeta alienígena hostil mientras luchas contra criaturas mortales y exploras ruinas antiguas.",
  "Participa en emocionantes carreras de automóviles y compite por ser el mejor piloto del mundo.",
  "Explora un mundo lleno de criaturas mágicas y descubre los secretos de la tierra de los sueños.",
  "Únete a un joven mago en su aventura para salvar el mundo de la oscuridad.",
  "Descubre los misterios de la antigua civilización de Mana y restaura el equilibrio del mundo.",
  "Adéntrate en la expansión final de la épica saga de Final Fantasy XIV y descubre un nuevo mundo de aventuras.",
  "Únete a un grupo de jóvenes psíquicos en una lucha por salvar el mundo de criaturas monstruosas.",
  "Embárcate en una emocionante aventura llena de acción en un mundo de ciencia ficción distópico.",
  "Descubre los secretos de un mundo futurista dominado por la tecnología y las criaturas biomecánicas.",
  "Lucha contra las fuerzas del mal en este juego de acción y aventuras lleno de combates intensos.",
  "Explora un mundo misterioso lleno de peligros y maravillas en busca de tu destino.",
  "Descubre los oscuros secretos de una ciudad encantada en este juego de acción y aventuras sobrenaturales.",
  "Únete a Kena en su viaje para restaurar el equilibrio del mundo y ayudar a los espíritus perdidos a encontrar la paz.",
  "Vive la experiencia de Hogwarts como nunca antes en este juego de rol de mundo abierto.",
  "Lucha contra una dictadura en una isla tropical en este juego de acción y aventuras lleno de acción.",
  "Explora los vastos paisajes de la Inglaterra medieval y vive la épica saga de los vikingos.",
  "Sumérgete en el peligroso mundo de la cybernetica y lucha por sobrevivir en las calles de Night City.",
  "Únete a la resistencia en un Londres distópico y lucha contra una corporación opresiva.",
  "Conviértete en el asesino más letal del mundo y elimina a tus objetivos con estilo.",
  "Enfréntate a tus peores pesadillas en esta escalofriante aventura de terror en primera persona.",
  "Explora un Tokio sobrenatural lleno de espíritus vengativos en este juego de acción y aventuras.",
  "Descubre los secretos de un mundo de fantasía lleno de criaturas mágicas y peligrosas.",
  "Embárcate en una emocionante aventura en un mundo lleno de dioses y monstruos en este juego de acción y aventuras.",
  "Explora el vasto y hermoso mundo de Hallownest en este juego de acción y aventuras lleno de peligros y maravillas.",
  "Lucha contra hordas de enemigos en este juego de acción desafiante con mecánicas de combate rápidas y fluidas.",
  "Explora un mundo mágico lleno de peligros y maravillas en busca de la verdad sobre tu destino.",
  "Embárcate en una emocionante aventura en un mundo de fantasía lleno de peligros y misterios.",
  "Cava, planta cultivos, cría animales y entabla amistad con los habitantes del pueblo en este relajante simulador de granja.",
  "Ayuda a los hermanos Cuphead y Mugman a salvar sus almas de las garras del diablo en este desafiante juego de plataformas y disparos.",
  "Embárcate en un viaje emocionante a través de un mundo lleno de personajes inolvidables y decisiones morales difíciles.",
];

export { products };
